---
roles:
  base_4gb_ram:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 4096]

  base_6gb_ram:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 6144]

  base_2_cpus:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--hpet', "on"]
        - [modifyvm, !ruby/sym id, '--ioapic', "on"]
        - [modifyvm, !ruby/sym id, '--cpus', 2]

  pe_puppet_master:
    private_networks:
      - {auto_network: true}
    forwarded_ports:
      - {guest: 443, host: 8443}
    provisioners:
      - {type: hosts, autoconfigure: true, add_localhost_hostnames: false}
      - {type: pe_bootstrap, role: !ruby/sym master}
      - type: shell
        inline: "sed -i -e '/^127/!s|'`hostname -s`'$|'`/opt/puppet/bin/facter fqdn`' '`hostname -s`'|' /etc/hosts"
      - type: shell
        inline: "/vagrant/pe_configure.sh"
    synced_folders:
      - {host_path: 'puppet/modules', guest_path: '/modules'}
      - {host_path: 'puppet/hieradata', guest_path: '/var/lib/hiera'}

  pe_puppet_agent:
    private_networks:
      - {auto_network: true}
    provisioners:
      - {type: hosts, autoconfigure: true, add_localhost_hostnames: false}
      - {type: pe_bootstrap}
      - type: shell
        inline: "sed -i -e '/^127/!s|'`hostname -s`'$|'`/opt/puppet/bin/facter fqdn`' '`hostname -s`'|' /etc/hosts"

  cm_server:
    forwarded_ports:
      - {guest: 7180, host: 7180, auto_correct: true}

  centos:
    provisioners:
      - type: shell
        inline: "chkconfig iptables off;service iptables stop;setenforce Permissive;true"
      - type: shell
        inline: "sed -i -e 's|^mirrorlist=|#mirrorlist=|' -e 's|^#baseurl=|baseurl=|' /etc/yum.repos.d/CentOS-Base.repo"

