---
vms:
- name: master
  #box: puppetlabs/centos-6.6-64-nocm
  box: chef/centos-6.6
  roles: [ "pe_puppet_master", "centos", "base_2_cpus", "base_6gb_ram" ]
  #roles: [ "base_6gb_ram", "base_2_cpus", "centos", "pe_puppet_master" ]
- name: node1
  box: chef/centos-6.6
  roles: [ "cm_server", "pe_puppet_agent", "centos", "base_2_cpus", "base_6gb_ram" ]
  #roles: [ "base_6gb_ram", "base_2_cpus", "centos", "pe_puppet_agent", "cm_server" ]
- name: node2
  box: chef/centos-6.6
  roles: [ "pe_puppet_agent", "centos", "base_2_cpus", "base_6gb_ram" ]
  #roles: [ "base_6gb_ram", "base_2_cpus", "centos", "pe_puppet_agent" ]
- name: node3
  box: chef/centos-6.6
  roles: [ "pe_puppet_agent", "centos", "base_2_cpus", "base_6gb_ram" ]
  #roles: [ "base_6gb_ram", "base_2_cpus", "centos", "pe_puppet_agent" ]
- name: node4
  box: chef/centos-6.6
  roles: [ "pe_puppet_agent", "centos", "base_2_cpus", "base_6gb_ram" ]
  #roles: [ "base_6gb_ram", "base_2_cpus", "centos", "pe_puppet_agent" ]
