---
vms:
- name: master
  box: puppetlabs/centos-6.5-64-nocm
  roles:
  - pe-puppet-master
- name: centos5
  box: puppetlabs/centos-5.11-64-nocm
  roles:
  - centos
- name: centos6
  box: puppetlabs/centos-6.5-64-nocm
  roles:
  - centos
- name: debian6
  box: debian-607-x64-vbox4210-nocm
#  box: puppetlabs/debian-6.0.9-64-nocm
  roles:
  - pe-puppet-agent
- name: debian7
#  box: debian-70rc1-x64-vbox4210-nocm
  box: puppetlabs/debian-7.6-64-nocm
  roles:
  - pe-puppet-agent
- name: sles11
  box: sles-11sp1-x64-vbox4210-nocm
  roles:
  - sles
- name: ubuntu1004
  box: ubuntu-server-10044-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent
- name: ubuntu1204
  box: puppetlabs/ubuntu-12.04-64-nocm
  roles:
  - pe-puppet-agent
- name: ubuntu1404
  box: puppetlabs/ubuntu-14.04-64-nocm
  roles:
  - pe-puppet-agent
